name: Rust

on:
  push:
    branches: ["main"]
  pull_request:

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always
  rust_min: 1.58.1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          - pinned
          - stable
          - nightly
        include:
          - build: pinned
            os: ubuntu-latest
            rust: 1.58.1
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: nightly
            os: ubuntu-latest
            rust: nightly
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust ${{ env.rust_min }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_min }}
          override: true
          components: rustfmt, clippy
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose
      - name: Doc
        run: cargo doc --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        if: matrix.build == 'stable'
        run: cargo clippy --all-targets --all-features -- -D warnings
